apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: Voting-App
spec:
  type: ClusterIP
  selector:
    name: db-pod
    app: Voting-App
  ports:
  - port: 5432
    targetPort: 5432