apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-pod
    app: Voting-App
spec:
  type: NodePort
  selector:
    name: result-pod
    app: Voting-App
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001