apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    name: vote-deployment
    app: Voting-App
spec:
  replicas: 2
  selector:
    matchLabels:
      name: vote-pod
      app: Voting-App
  template:
    metadata:
      name: vote-pod
      labels:
        name: vote-pod
        app: Voting-App
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 80