apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-pod
    app: Voting-App
spec:
  type: NodePort
  selector:
    name: vote-pod
    app: Voting-App
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
